volumes:
  mongodbvol:
  jupyter:

services:
  # app:
  #   build: .
  #   command: python server.py
  #   depends_on:
  #     - redis
  #   ports:
  #     - 5555:5000
  #   volumes:
  #     - .:/app
  jupyter:
    build: .
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8889:8888
    volumes:
      - ./notebooks:/app

  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

    ports:
      - 6379:6379

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodbvol:/data/db
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/